### ISSUE TITLE
Add #aragon-boilerplate tag to the repo

### ISSUE THREAD

**Issue by sembrestels** [aragon/aragon-app-dx#3]
Add a _#aragon-boilerplate_ tag to this repo in order to make it findable from other boilerplates' READMEs:

> 🕵️ [Find more boilerplates using GitHub](https://github.com/search?q=topic:aragon-boilerplate) | ✨ [Official boilerplates](https://github.com/search?q=topic:aragon-boilerplate+org:aragon)

**Comment by sohkai** [comment]
This repo isn't meant to be used as a boilerplate; we will update the existing boilerplates once the improvements in this repo have been implemented.
